name = "Chiefy"
author = "Enderchief"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf6cb3e5ba48d147e26baf5d66ccb07ad966437ba821c66e9a012036aa37e521"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
